### ISSUE TITLE
Wrong administration protocol in simulation Pourbaix 1985 - alprazolam 0.5 mg TID + cimetidine 200/400 mg QID

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Cimetidine-Alprazolam-DDI#4]
@TWendl 
Start time needs to be 336 h (and is currently 168 as in the respective control simulation):

![image](https://user-images.githubusercontent.com/26569320/101462360-70e7ea00-393c-11eb-988e-2824e5caea4d.png)

**Comment by TWendl** [comment]
this goes back to the reported PK-Sim bug here:
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1601
@Yuri05 please take care!
